Issue#73 FollowService 추가
Studyvelopers/OverTheFlow pull request #74
Opened 2019-08-14 03:54 UTC by kjs775

2019-08-14 10:19 UTC, dhjeon1993 requested changes
자바독 주석을 인터페이스에 달아주시고 컨트롤러 파일은 지워주세요.

2019-08-14 10:19 UTC, dhjeon1993 commented on src/main/java/com/studyveloper/overtheflow/service/MemberServiceImpl.java
> +
자바독 주석은 인터페이스에 달아주세요

2019-08-14 12:46 UTC, kjs775 commented on src/main/java/com/studyveloper/overtheflow/service/MemberServiceImpl.java
> +
수정 했습니다

2019-08-19 03:39 UTC, LJG070 approved these changes
확인 완료

2019-08-28 03:28 UTC, merged

2019-08-28 03:28 UTC, dhjeon1993 approved these changes
확인 완료.